# version: '3.8'
# services:
#   flask:
#     build: 
#       context: .
#       dockerfile: Dockerfile
#     environment:
#       ## In case to go prod remove this requirement  
#       - FLASK_DEBUG=true
#       ## Allows to see the work in command line
#       - PYTHONUNBUFFERED=True                   
#     ## Restarn on failure
#     restart: on-failure
#     ## Duplicating files in docker container folder
#     volumes:
#       - .:/app
#     ## Port, which will be listened from the outside : Port within the container
#     ports:
#       - "5000:5000"
# #     networks:
# #       meshroom-service_my_network:
# #     ## Ipv4_adress of machine
        
    
# # networks:
# #   meshroom-service_my_network:
# #     driver: bridge


version: '3'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    networks:
      mynetwork:
        ipv4_address: 192.168.137.1

networks:
  mynetwork:
    ipam:
      driver: default
      config:
        - subnet: 192.168.137.0/14